{
  domain {
    id
    name
    macroProcesses (order: {
      name: ASC
    }) {
      id
      name 
      processes(order: {
      name: ASC
    }) {
        id
        name
        activities(order: {
      name: ASC
    }) {
          id
          name
        }
      }
    }
  }
}